### ISSUE TITLE
Read user config file from home directory

### ISSUE THREAD

**Issue by smrohrer** [wikitongues/Language-Indexing#13]
* In addition to config/indexing.cfg, the program should read a config file from the home directory
* This allows users to keep a config file that won't be checked in to the git repository, so it can be used to store API keys, fine-tune specific crawling sessions, etc.
* Let's call it wikitongues-language-indexing.cfg
* config/indexing.cfg will be used to provide some default settings
* The user config will be in the same format as indexing.cfg
* Settings in the user config file will override settings from indexing.cfg

**Comment by madamc** [comment]
@smrohrer,does home directory refer to the root of the project or the actual local users' home folder or windows equivalent?

**Comment by smrohrer** [comment]
It should be the user’s home folder. The idea is to use it to configure things that shouldn’t be checked in to the repository, such as API keys or one-time run configurations
