### ISSUE TITLE
Create utility for writing user config file

### ISSUE THREAD

**Issue by smrohrer** [wikitongues/Language-Indexing#31]
- Prompt for “fake” property
- Prompt for base id and api key of each table
- Prompt for page size, max records
- Write file to %appdata%\wikitongues-language-indexing.cfg on Windows; ~/wikitongues-language-indexing.cfg on Mac/linux
- Check if file already exists, prompt to overwrite

**Comment by d28601581** [comment]
Should the fake, base id ,api key, page, size, and max records be different for both tables? Also should the user file have these properties uncommented in the tables?

[airtable_languages_table]
# Uncomment below to override
table_name : Languages
id_column : Identifier
page_size : 100
# max_records : 10
# base_id : {your base id}
# api_key : {your api key}
# fake : true

[airtable_items_table]
table_name : External Resources
id_column : Url
page_size : 100
# max_records : 10
# base_id : {your base id}
# api_key : {your api key}
# fake : true

[DEFAULT]
# MODIFY
base_id : {your base id}
api_key : {your api key}
# DO NOT MODIFY
fake : False
max_records
